### ISSUE TITLE
Adding support for todo assignee

### ISSUE THREAD

**Issue by alirezamirian** [pgilad/gulp-todo#46]
Gulp-todo, nice idea!
How about adding support for separate outputs based on todo assignee. It's common to have todos like: TODO(alireza): ...

**Comment by pgilad** [comment]
First off, the parser that `gulp-todo` uses is [leasot](https://github.com/pgilad/leasot). So that feature request should probably be there. Regarding adding assignee - it's not difficult, but I also know some people who use `TODO(:category): do something` so you would end with highly complex parsing in order to correctly parse each format. You can try adding your own alternative parser and add a PR if it works well!

Closing this for now, feel free to add a feature-request to `leasot`

**Comment by alirezamirian** [comment]
@pgilad 
Thanks,
BTW, I don't think of it as a complex parsing problem because no matter it's **category** or **assignee**, having a feature for grouping TODOs based on that would be nice.
